#!/bin/bash
# Usage: ./run_PDPTW class name max_trials runs [ optimum ]

if [ -z "$4" ]; then
    echo "./run_PDPTW class name max_trials runs [ optimum ]"
    exit
fi

lkh="../../LKH"
class=$1
name=$2
max_trials=$3
runs=$4
optimum=$5
par=TMP/$name.pid$$.par

mkdir -p TOURS
mkdir -p TOURS/$class
mkdir -p TMP

echo "SPECIAL" > $par
echo "PROBLEM_FILE = INSTANCES/$class/$name.pdptw" >> $par
echo "MAX_TRIALS = $max_trials" >> $par
echo "RUNS = $runs" >> $par
echo "TOUR_FILE = TOURS/$class/$name.$.tour" >> $par
#echo "OUTPUT_TOUR_FILE = tour.txt" >> $par
echo "TRACE_LEVEL = 1" >> $par
echo "CANDIDATE_SET_TYPE = POPMUSIC" >> $par

# if [ -n "$optimum" ]; then
#     echo "OPTIMUM = $optimum" >> $par
# fi

$lkh $par

#/bin/rm -f $par
